### ISSUE TITLE
Sample failed to run, Job return code is 174

### ISSUE THREAD

**Issue by drakeyu** [Matgenix/pysisso#24]
Hi,
Thanks for sharing. I am currently running SISSO for examplaes you shared, when I ran the cubic_function.py in the 01_regresion folder, it gave me the following message:
Job return code is 174. Terminating...
Traceback (most recent call last):
  File "cubic_function.py", line 71, in <module>
    sisso_regressor.fit(X, y)
  File "/home/zihanyu/anaconda2/envs/py36/lib/python3.6/site-packages/pysisso/sklearn.py", line 271, in fit
    c.run()
  File "/home/zihanyu/anaconda2/envs/py36/lib/python3.6/site-packages/custodian/custodian.py", line 372, in run
    self._run_job(job_n, job)
  File "/home/zihanyu/anaconda2/envs/py36/lib/python3.6/site-packages/custodian/custodian.py", line 510, in _run_job
    raise ReturnCodeError(s, True)
custodian.custodian.ReturnCodeError: Job return code is 174. Terminating...
I am not sure where I did wrong and I don't see any solution for that. May I get some help for that? Thanks！

**Comment by davidwaroquiers** [comment]
Hi,

Could you make sure that the sisso executable is "SISSO" (in the sklearn interface, the executable has to be available in the path and has to be named "SISSO", this is something that could be changed in a future version). Just type "which SISSO" in a terminal to see if it is indeed available.

Best,

David

**Comment by drakeyu** [comment]
Hi,
Thanks for replying! I am pretty sure that the SISSO executable is available in the path. I added "export PATH="/path_to_SISSO:$PATH" " so when I typed which SISSO is shows the path I entered. Is the way I did wrong? Thanks!

**Comment by davidwaroquiers** [comment]
Hi,

Could you try running SISSO on its own with the generated input files in the directory ? Just to see if it is a SISSO problem or a python problem.

Best,

David

**Comment by drakeyu** [comment]
Hi,
I am not familiar with fortran but when I followed the instruction of SISSO and run it on the input_template and it will gave me the following message: 
(base) [zihanyu@chestnut-login example]$ mpirun -np 1 SISSO.exe>log
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
SISSO.exe          0000000000536511  Unknown               Unknown  Unknown
SISSO.exe          000000000053464B  Unknown               Unknown  Unknown
SISSO.exe          00000000004E1C84  Unknown               Unknown  Unknown
SISSO.exe          00000000004E1A96  Unknown               Unknown  Unknown
SISSO.exe          000000000048E599  Unknown               Unknown  Unknown
SISSO.exe          0000000000492056  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F098696E630  Unknown               Unknown  Unknown
SISSO.exe          00000000004847A5  Unknown               Unknown  Unknown
SISSO.exe          0000000000481C44  Unknown               Unknown  Unknown
SISSO.exe          00000000004030DE  Unknown               Unknown  Unknown
libc-2.17.so       00007F09862B1555  __libc_start_main     Unknown  Unknown
SISSO.exe          0000000000402FE9  Unknown               Unknown  Unknown

I am not sure if I did this right.. Thanks for the help!

**Comment by davidwaroquiers** [comment]
Hi,

So this seems to be more of a SISSO error (unless the files generated by pysisso are wrong). Could you post the files generated by pysisso here and I'll check on my side.

Best


David

**Comment by drakeyu** [comment]
Hi David,
I have posted files on this google drive:
https://drive.google.com/drive/folders/1n_R1aLO1gpKU5KTa8pCLOPctDU-JnEMV?usp=sharing
Thanks for the help!

**Comment by halexandrino** [comment]
Hi!
Thank you so much for sharing with us!
I have been facing the same problem, running the same example on the Jupyter notebook.
The message below appears:

**ValueError:** SISSOJob requires the SISSO executable to be in the path.
Default executable name is "SISSO" and you provided "SISSO".
Download the SISSO code at https://github.com/rouyang2017/SISSO and compile the executable or fix the name of your executable.

I have some questions (I'm not very familiar with coding):
is the executable SISSO my jupyter file, or does it have a SISSO.exe file?
Is the path a folder where sisso is installed in conda/env… or should my jupyter file be in a specific folder?

Thank you very much in advance

**Comment by chr218** [comment]
> Hi, I am not familiar with fortran but when I followed the instruction of SISSO and run it on the input_template and it will gave me the following message: (base) [zihanyu@chestnut-login example]$ mpirun -np 1 SISSO.exe>log forrtl: severe (174): SIGSEGV, segmentation fault occurred Image PC Routine Line Source SISSO.exe 0000000000536511 Unknown Unknown Unknown SISSO.exe 000000000053464B Unknown Unknown Unknown SISSO.exe 00000000004E1C84 Unknown Unknown Unknown SISSO.exe 00000000004E1A96 Unknown Unknown Unknown SISSO.exe 000000000048E599 Unknown Unknown Unknown SISSO.exe 0000000000492056 Unknown Unknown Unknown libpthread-2.17.s 00007F098696E630 Unknown Unknown Unknown SISSO.exe 00000000004847A5 Unknown Unknown Unknown SISSO.exe 0000000000481C44 Unknown Unknown Unknown SISSO.exe 00000000004030DE Unknown Unknown Unknown libc-2.17.so 00007F09862B1555 __libc_start_main Unknown Unknown SISSO.exe 0000000000402FE9 Unknown Unknown Unknown
> 
> I am not sure if I did this right.. Thanks for the help!

try executing:

ulimit -s unlimited

before running SISSO. It worked for me.
