### ISSUE TITLE
ERROR while running pysisso

### ISSUE THREAD

**Issue by shan872** [Matgenix/pysisso#29]
Hi there,

I am trying to run the "cubic_function.py" example however, I am facing an issue while running it.
First, an issue with the SISSO executable is not available. Then, after some search on the internet, I found a suggestion to add the SISSO executable to the path as an environment variable. But then some other error popped up, as mentioned below. 
------------------------------------
Traceback (most recent call last):
  File "D:/MTP/Calculations/python script/databases.py", line 72, in <module>
    sisso_regressor.fit(X, y)
  File "D:\MTP\Calculations\python script\lib\site-packages\pysisso\sklearn.py", line 271, in fit
    c.run()
  File "D:\MTP\Calculations\python script\lib\site-packages\custodian\custodian.py", line 372, in run
    self._run_job(job_n, job)
  File "D:\MTP\Calculations\python script\lib\site-packages\custodian\custodian.py", line 450, in _run_job
    p = job.run()
  File "D:\MTP\Calculations\python script\lib\site-packages\pysisso\jobs.py", line 72, in run
    p = subprocess.Popen(cmd, stdin=None, stdout=f_stdout, stderr=f_stderr)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
---------------------------------------------

Could anyone please guide me towards resolving the issue.

Thanks

**Comment by lyapunovlcl** [comment]
I have a question : How to add the SISSO executable to the path as an environment variable? Thanks!
